const express=require('express'),path=require('path'),fs=require('fs'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),cookieParser=require('cookie-parser');
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'CHANGE_SECRET',DB=path.join(__dirname,'data.json');
const read=()=>{try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch{return {admins:[],posts:[]}}};const write=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2));let db=read();
if(!db.admins.length){db.admins.push({id:1,username:process.env.ADMIN_USER||'admin',passwordHash:bcrypt.hashSync(process.env.ADMIN_PASSWORD||'CHANGE_ME_NOW',12)});write(db)}
app.use(express.json());app.use(cookieParser());app.use(express.static(__dirname));
function auth(req,res,next){try{const t=req.cookies.fjs_token;if(!t)return res.status(401).json({error:'Login required'});req.admin=jwt.verify(t,SECRET);next()}catch{return res.status(401).json({error:'Invalid session'})}}
app.post('/api/login',(req,res)=>{const {username,password}=req.body||{},a=db.admins.find(x=>x.username===username);if(!a||!bcrypt.compareSync(password||'',a.passwordHash))return res.status(401).json({error:'Invalid username or password'});const t=jwt.sign({id:a.id,username:a.username},SECRET,{expiresIn:'8h'});res.cookie('fjs_token',t,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:28800000});res.json({ok:true})});
app.post('/api/logout',(req,res)=>{res.clearCookie('fjs_token');res.json({ok:true})});app.get('/api/me',auth,(req,res)=>res.json({username:req.admin.username}));
app.get('/api/posts',(req,res)=>{let p=db.posts.slice().reverse();if(req.query.type)p=p.filter(x=>x.type===req.query.type);res.json(p)});
app.post('/api/posts',auth,(req,res)=>{const {type,title,organization='',category='',last_date='',details='',official_link=''}=req.body||{};if(!['job','result','admit','notice'].includes(type)||!title)return res.status(400).json({error:'Type and title are required'});const id=(db.posts.at(-1)?.id||0)+1;db.posts.push({id,type,title,organization,category,last_date,details,official_link,created_at:new Date().toISOString()});write(db);res.json({id})});
app.delete('/api/posts/:id',auth,(req,res)=>{db.posts=db.posts.filter(p=>p.id!==Number(req.params.id));write(db);res.json({ok:true})});app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));app.listen(PORT,()=>console.log('FastJobSerch running on '+PORT));
